// 默认路由表
export default [
  { text: "html", link: "/html" },
  { text: "css", link: "/css" },
  { text: "js", link: "/js" },
  { text: "ts", link: "/ts" },
  { text: "vue2", link: "/vue2" },
  { text: "vue3", link: "/vue3" },
  { text: "react", link: "/react" },
  { text: "node", link: "/node" },
  { text: "python", link: "/python" },
  { text: "http", link: "/http" },
  { text: "AI", link: "/ai" },
  { text: "浏览器原理", link: "/browser" },
  { text: "数据库", link: "/database" },
  { text: "系统设计", link: "/system-design" },
  { text: "安全", link: "/security" },
  { text: "DevOps", link: "/devops" },
  { text: "移动端", link: "/mobile" },
  { text: "场景题", link: "/scenario-based" },
  { text: "前端工程化", link: "/fe-engineering" },
  { text: "手写题", link: "/code" },
  { text: "算法", link: "/algorithm" },
];
